# Generated by Django 3.2.10 on 2023-02-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_disrtibuterdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddb',
            name='Price',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='disrtibuterdb',
            name='Address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
