# Generated by Django 3.2.10 on 2023-02-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20230218_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='breeddb',
            name='Distributer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
