# Generated by Django 3.2.10 on 2023-02-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_cartdb_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(blank=True, max_length=50, null=True)),
                ('Lname', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('Country', models.CharField(blank=True, max_length=100, null=True)),
                ('State', models.CharField(blank=True, max_length=100, null=True)),
                ('Pin', models.IntegerField(blank=True, max_length=100, null=True)),
                ('NOC', models.CharField(blank=True, max_length=100, null=True)),
                ('CCN', models.CharField(blank=True, max_length=100, null=True)),
                ('Expiration', models.CharField(blank=True, max_length=100, null=True)),
                ('CVV', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
