# Generated by Django 3.2.10 on 2023-02-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='CCN',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='CVV',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='Expiration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='Pin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
