# Generated by Django 3.2.10 on 2023-03-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20230223_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='Food',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='Expiration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
