# Generated by Django 3.2.10 on 2023-02-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savelogindb',
            name='Email',
        ),
        migrations.AddField(
            model_name='savelogindb',
            name='Confirm',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
